<?php

namespace Lefeto\ReservationBundle\Repository;

/**
 * TypeLogementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLogementRepository extends \Doctrine\ORM\EntityRepository
{
}
